// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace TestClusterProj.Models;

public partial class ClusterContext : DbContext
{
    public ClusterContext(DbContextOptions<ClusterContext> options)
        : base(options)
    {
    }

    public virtual DbSet<WgeAmrtamperStaging> WgeAmrtamperStagings { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<WgeAmrtamperStaging>(entity =>
        {
            entity
                .HasNoKey()
                .ToTable("WGE_AMRTamperStaging");

            entity.Property(e => e.Category).IsUnicode(false);
            entity.Property(e => e.DiscTime).HasColumnType("datetime");
            entity.Property(e => e.EventTime).HasColumnType("datetime");
            entity.Property(e => e.MeterName)
                .HasMaxLength(25)
                .IsUnicode(false);
            entity.Property(e => e.TamperType)
                .HasMaxLength(50)
                .IsUnicode(false);
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}